CREATE TABLE `CDept5` (
  `co` varchar(10) NOT NULL,
  `cc5` varchar(10) NOT NULL,
  `name` varchar(50) NULL,
  `address1` varchar(50) NULL,
  `address2` varchar(50) NULL,
  `city` varchar(30) NULL,
  `state` varchar(20) NULL,
  `zip` varchar(10) NULL,
  `county` varchar(30) NULL,
  `country` varchar(30) NULL,
  `overrideCheckCalcCode` varchar(10) NULL,
  `wcc` varchar(10) NULL,
  `overrideRateCode` varchar(10) NULL,
  `overrideRate` decimal(14,6) NULL,
  `overrideShift` varchar(10) NULL,
  `overrideCheckAcctName` varchar(40) NULL,
  `guidfield` char(36) NOT NULL,
  `lastChange` datetime NOT NULL,
  `lastChangeUser` varchar(50) NOT NULL,
  CONSTRAINT `PK_CDept5` PRIMARY KEY (`co`, `cc5`),
  CONSTRAINT `UQ_CDept5_guidfield` UNIQUE (`guidfield`),
  KEY `IX_APS_CDept5_CoCC5` (`co`, `cc5`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
