CREATE TABLE `CEarn` (
  `co` varchar(10) NOT NULL,
  `ecode` varchar(10) NOT NULL,
  `description` varchar(200) NULL,
  `shortDescription` varchar(10) NULL,
  `eamType` varchar(15) NULL,
  `w2Field` varchar(5) NULL,
  `printOnCheckStub` char(1) NULL,
  `minimum` decimal(14,2) NULL,
  `maximum` decimal(14,2) NULL,
  `annualMaximum` decimal(14,2) NULL,
  `overrideRate` decimal(14,6) NULL,
  `addToRate` decimal(14,6) NULL,
  `rateMultiplier` decimal(14,6) NULL,
  `overrideShift` varchar(10) NULL,
  `unitDescription` varchar(10) NULL,
  `autoDrop` char(1) NOT NULL DEFAULT 'N',
  `reduceAutoPay` char(1) NOT NULL DEFAULT 'N',
  `guidfield` char(36) NOT NULL,
  `lastChange` datetime NOT NULL,
  `lastChangeUser` varchar(50) NOT NULL DEFAULT '',
  `Obsolete` char(1) NOT NULL DEFAULT 'N',
  `worked` char(1) NOT NULL DEFAULT 'N',
  CONSTRAINT `PK_CEarn` PRIMARY KEY (`co`, `ecode`),
  CONSTRAINT `UQ_CEarn_guidfield` UNIQUE (`guidfield`),
  KEY `IX_APS_CEarn_ecodeCo_inc_DescriptionDedType` (`co`, `ecode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
